
package app;

/**
 *
 * @author ITurbo
 */
public class Mostused extends javax.swing.JInternalFrame {

    /**
     * Creates new form TodaysOccupation
     */
    public Mostused() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jPanelTO = new javax.swing.JPanel();

            setClosable(true);
            setTitle("Most used services");
            setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mostused.png"))); // NOI18N

            jPanelTO.setToolTipText("");

            javax.swing.GroupLayout jPanelTOLayout = new javax.swing.GroupLayout(jPanelTO);
            jPanelTO.setLayout(jPanelTOLayout);
            jPanelTOLayout.setHorizontalGroup(
                  jPanelTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 394, Short.MAX_VALUE)
            );
            jPanelTOLayout.setVerticalGroup(
                  jPanelTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 274, Short.MAX_VALUE)
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jPanelTO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jPanelTO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents


      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JPanel jPanelTO;
      // End of variables declaration//GEN-END:variables
}
