package app;

import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author ITurbo
 */
public class View extends javax.swing.JFrame {

   
     

      public View() {
            initComponents();
            jPanel.setVisible(false);

      }
      public static View viewCreate() {
        View v = new View();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                v.setVisible(true);
            }
        });
        return v;
      }

      /**
       * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jPanel = new javax.swing.JPanel();
            jLabelCarSiloutte = new javax.swing.JLabel();
            jLabelWelcome = new javax.swing.JLabel();
            jMenuBar = new javax.swing.JMenuBar();
            jMenuReports = new javax.swing.JMenu();
            jMenuItemTodays = new javax.swing.JMenuItem();
            jMenuItemFacturation = new javax.swing.JMenuItem();
            jMenuItemMostUsed = new javax.swing.JMenuItem();
            jMenuItemAmount = new javax.swing.JMenuItem();
            jMenuAbout = new javax.swing.JMenu();
            jMenuItemAbout = new javax.swing.JMenuItem();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("ITurboAPP");
            setIconImage(new ImageIcon("./icon/ICON_Main.png").getImage());
            setResizable(false);
            setType(java.awt.Window.Type.UTILITY);

            jPanel.setBackground(new java.awt.Color(255, 102, 102));

            javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
            jPanel.setLayout(jPanelLayout);
            jPanelLayout.setHorizontalGroup(
                  jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 614, Short.MAX_VALUE)
            );
            jPanelLayout.setVerticalGroup(
                  jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 411, Short.MAX_VALUE)
            );

            jLabelCarSiloutte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabelCarSiloutte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carSiloutte.png"))); // NOI18N

            jLabelWelcome.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
            jLabelWelcome.setForeground(new java.awt.Color(255, 51, 51));
            jLabelWelcome.setText("WELCOME TO OUR DIY GARAGE");

            jMenuReports.setText("Reports");

            jMenuItemTodays.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/todaysocupation.png"))); // NOI18N
            jMenuItemTodays.setText("Today´s occupation");
            jMenuItemTodays.setActionCommand("TO");
            jMenuItemTodays.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemTodaysActionPerformed(evt);
                  }
            });
            jMenuReports.add(jMenuItemTodays);

            jMenuItemFacturation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/facturation.png"))); // NOI18N
            jMenuItemFacturation.setText("Facturation");
            jMenuItemFacturation.setActionCommand("FACTU");
            jMenuItemFacturation.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemFacturationActionPerformed(evt);
                  }
            });
            jMenuReports.add(jMenuItemFacturation);

            jMenuItemMostUsed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mostused.png"))); // NOI18N
            jMenuItemMostUsed.setText("Most used service");
            jMenuItemMostUsed.setActionCommand("MUS");
            jMenuItemMostUsed.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemMostUsedActionPerformed(evt);
                  }
            });
            jMenuReports.add(jMenuItemMostUsed);

            jMenuItemAmount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/customerspermonth-day.png"))); // NOI18N
            jMenuItemAmount.setText("Amount of customers");
            jMenuItemAmount.setActionCommand("AOC");
            jMenuItemAmount.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemAmountActionPerformed(evt);
                  }
            });
            jMenuReports.add(jMenuItemAmount);

            jMenuBar.add(jMenuReports);

            jMenuAbout.setText("About");

            jMenuItemAbout.setText("About...");
            jMenuItemAbout.setActionCommand("ABOUT");
            jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jMenuItemAboutActionPerformed(evt);
                  }
            });
            jMenuAbout.add(jMenuItemAbout);

            jMenuBar.add(jMenuAbout);

            setJMenuBar(jMenuBar);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                              .addGap(16, 16, 16)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                          .addGap(41, 41, 41)
                                          .addComponent(jLabelCarSiloutte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addGap(32, 32, 32)))
                              .addGap(17, 17, 17)))
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                              .addGap(76, 76, 76)
                              .addComponent(jLabelWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addGap(43, 43, 43)
                              .addComponent(jLabelCarSiloutte, javax.swing.GroupLayout.PREFERRED_SIZE, 151, Short.MAX_VALUE)
                              .addGap(100, 100, 100)))
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemTodaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTodaysActionPerformed
   
    }//GEN-LAST:event_jMenuItemTodaysActionPerformed

    private void jMenuItemFacturationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFacturationActionPerformed
   
    }//GEN-LAST:event_jMenuItemFacturationActionPerformed

    private void jMenuItemMostUsedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMostUsedActionPerformed
    
    }//GEN-LAST:event_jMenuItemMostUsedActionPerformed

    private void jMenuItemAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAmountActionPerformed
   
    }//GEN-LAST:event_jMenuItemAmountActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
          
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

      /**
       * @param args the command line arguments
       */
      

      // Variables declaration - do not modify//GEN-BEGIN:variables
      public javax.swing.JLabel jLabelCarSiloutte;
      public javax.swing.JLabel jLabelWelcome;
      public javax.swing.JMenu jMenuAbout;
      public javax.swing.JMenuBar jMenuBar;
      public javax.swing.JMenuItem jMenuItemAbout;
      public javax.swing.JMenuItem jMenuItemAmount;
      public javax.swing.JMenuItem jMenuItemFacturation;
      public javax.swing.JMenuItem jMenuItemMostUsed;
      public javax.swing.JMenuItem jMenuItemTodays;
      public javax.swing.JMenu jMenuReports;
      public javax.swing.JPanel jPanel;
      // End of variables declaration//GEN-END:variables
}
